# Use the official Python image
FROM python:3.13-slim

# Install uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Install the project into /app
COPY dataset/data/milvus.db /app/dataset/data/milvus.db
COPY mcp_server/ /app/
WORKDIR /app

# Install dependencies
# TODO: Optimise dependencies 
COPY mcp_pyproject.toml pyproject.toml
RUN uv sync

# Port where the app will run 
EXPOSE 9000

# Run the FastMCP server
CMD ["uv", "run", "main.py"]
